# Server Configuration
server:
  address: 0.0.0.0
  port: 7500

# Log Configuration
logging:
  file:
    path: "./logs"

# Cloudflare Captcha Configuration
captcha:
  secret: "CHANGE_ME"

# QuestDB Configuration (Metrics)
questdb:
  enabled: false
  uri: "http::addr=localhost:9000;username=tether;password=p4$$w0rd;auto_flush_interval=5000;"

# Sentry Configuration
sentry:
  dsn: "" # Leave blank for no sentry
  tracesSampleRate: 1.0
  environment: "development"

# Spring Configuration
spring:
  data:
    # MongoDB Configuration
    mongodb:
      uri: "mongodb://pulseapp:p4$$w0rd@localhost:27017/pulseapp?authSource=admin"
      auto-index-creation: true # Automatically create collection indexes

  # Don't serialize null values by default with Jackson
  jackson:
    default-property-inclusion: non_null

  # Ignore
  banner:
    location: "classpath:banner.txt"