name: Deploy API

on:
  push:
    branches: ["master"]
    paths-ignore:
      - README.md
      - LICENSE

jobs:
  deploy:
    strategy:
      matrix:
        arch: ["ubuntu-latest"]
        git-version: ["2.44.0"]
    runs-on: ${{ matrix.arch }}

    # Steps to run
    steps:
      # Checkout the repo
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      # Deploy to Dokku
      - name: Deploy to Dokku
        uses: dokku/github-action@master
        with:
          git_remote_url: "ssh://dokku@10.10.70.73:22/api"
          ssh_private_key: ${{ secrets.DOKKU_SSH_PRIVATE_KEY }}